# Generated by Django 4.2 on 2023-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_comments_comment_rating_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='University_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.ImageField(default=None, null=True, upload_to='avt/%Y/%m')),
                ('website_url', models.TextField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
